"""Default values for all app settings."""

# General
DEFAULT_START_ON_BOOT = False
DEFAULT_CHECK_FOR_UPDATES = True
DEFAULT_SHOW_BOOT_NOTIFICATION = True
DEFAULT_PLAY_COMPLETION_SOUND = True
DEFAULT_POSITION_LOCKED = False
DEFAULT_PINNED_TO_DESKTOP = False
DEFAULT_ALWAYS_ON_TOP = False

# Appearance
DEFAULT_THEME = "dark"
DEFAULT_OPACITY = 1.0
DEFAULT_TASK_TEXT_SIZE = 14
DEFAULT_TASK_FONT = "Default (System)"
DEFAULT_MOUSE_GLOW = True

# Advanced
DEFAULT_GROUPS_ENABLED = False
DEFAULT_TAG_FILTER_ENABLED = False
DEFAULT_HISTORY_RETENTION_DAYS = 30

# Shortcuts
DEFAULT_HISTORY_SHORTCUT = "Ctrl+H"
DEFAULT_SETTINGS_SHORTCUT = "Ctrl+,"
DEFAULT_PIN_SHORTCUT = "Ctrl+P"
DEFAULT_ALWAYS_ON_TOP_SHORTCUT = "Alt+T"
DEFAULT_TOGGLE_TRAY_SHORTCUT = "Ctrl+M"
DEFAULT_EXPORT_SHORTCUT = "Ctrl+E"
DEFAULT_REMINDERS_SHORTCUT = "Alt+R"
