"""
Centralised constants for the Nudge app.

All magic numbers, hardcoded sizes, timer intervals, and layout values
are defined here. Import from this module instead of scattering literals
throughout the codebase.
"""

# ── Window & Dialog Sizes ─────────────────────────────────────────────
# Format: (default_w, default_h, min_w, min_h)

MAIN_WINDOW_DEFAULT = (300, 300)
MAIN_WINDOW_MIN = (280, 280)

HISTORY_DIALOG_DEFAULT = (420, 520)
HISTORY_DIALOG_MIN = (320, 380)

SETTINGS_DIALOG_DEFAULT = (500, 560)
SETTINGS_DIALOG_MIN = (400, 460)

TUTORIAL_DIALOG_DEFAULT = (400, 420)
TUTORIAL_DIALOG_MIN = (340, 360)
TUTORIAL_OVERLAP_RADIUS = 20
TUTORIAL_MAIN_LAYOUT_MARGINS = (20, 20, 20, 20)
TUTORIAL_PAGE_MARGINS = (5, 5, 5, 5)
TUTORIAL_BLOCK_SPACING = 2
TUTORIAL_TEXT_OPACITY = 0.7

REMINDER_DIALOG_DEFAULT = (420, 320)
REMINDER_DIALOG_MIN = (380, 280)
REMINDER_OVERLAP_RADIUS = 12
REMINDER_MAIN_LAYOUT_MARGINS = (18, 16, 18, 14)
REMINDER_DEFAULT_REPEAT_MIN = 30
REMINDER_DEFAULT_HOUR = 9
REMINDER_DEFAULT_MINUTE = 0
REMINDER_BUTTON_SPACING = 12
REMINDERS_LIST_MAIN_LAYOUT_MARGINS = (16, 12, 16, 12)
REMINDERS_LIST_CLOSE_BTN_SIZE = (20, 20)
REMINDERS_LIST_EMPTY_STATE_SIZE = (280, 105)
REMINDERS_LIST_FILLED_STATE_SIZE = (380, 320)
REMINDERS_LIST_MIN_HEIGHT = 140
DUE_DATE_DIALOG_SIZE = (320, 300)
DUE_DATE_MAIN_LAYOUT_MARGINS = (12, 12, 12, 12)
RECURRENCE_DIALOG_SIZE = (300, 200)
RECURRENCE_MAX_COUNT = 365
RECURRENCE_MIN_COUNT = 1

TIMER_DIALOG_DEFAULT = (480, 340)
TIMER_DIALOG_MIN = (400, 280)

TIMER_EDIT_DIALOG_DEFAULT = (320, 200)
TIMER_EDIT_DIALOG_MIN_WIDTH = 280
TIMER_MAIN_LAYOUT_MARGINS = (16, 16, 16, 16)
TIMER_DIALOG_BTN_HEIGHT = 30
TIMER_DEFAULT_INTERVAL_S = 300
SECONDS_PER_MINUTE = 60
TIMER_MAX_INTERVAL_MIN = 1440
TIMER_MIN_INTERVAL_MIN = 1

UPDATE_INFO_DIALOG_DEFAULT = (420, 480)
UPDATE_INFO_DIALOG_MIN = (320, 360)

DOWNLOAD_DIALOG_DEFAULT = (380, 180)
DOWNLOAD_DIALOG_MIN = (300, 160)

EXPORT_DIALOG_DEFAULT = (380, 420)
EXPORT_DIALOG_MIN = (320, 360)

CRASH_DIALOG_MIN = (500, 350)
CRASH_DIALOG_SIZE = (450, 320)
CRASH_MAIN_LAYOUT_MARGINS = (24, 24, 24, 24)
CRASH_LAYOUT_SPACING = 12
CRASH_ICON_FONT_SIZE = 48
CRASH_TITLE_FONT_SIZE = 20
CRASH_ICON_HEIGHT = 56
CRASH_DETAILS_TEXT_HEIGHT = 160
CRASH_DETAIL_RESIZE_OFFSET = 160
CRASH_COPIED_RESET_MS = 2000

WHATS_NEW_DIALOG_DEFAULT = (400, 380)
WHATS_NEW_DIALOG_MIN = (320, 300)

SUPPORT_DIALOG_DEFAULT = (340, 260)
SUPPORT_DIALOG_MIN = (280, 220)
SUPPORT_LAYOUT_SPACING = 12
SUPPORT_TITLE_FONT_SIZE = 18
SUPPORT_DONATE_BTN_MIN_HEIGHT = 40

FEEDBACK_DIALOG_DEFAULT = (560, 460)
FEEDBACK_DIALOG_MIN = (420, 380)

MESSAGE_DIALOG_DEFAULT = (350, 150)
MESSAGE_DIALOG_MIN_WIDTH = 360
MESSAGE_MIN_WIDTH_FLOOR = 320
MESSAGE_CONTENT_PAD_H = 40
MESSAGE_SIZING_HEIGHT = 160
MESSAGE_BTN_GAP = 8
MESSAGE_LAYOUT_SPACING = 12
MESSAGE_DIALOG_BOTTOM_PAD = 8
INPUT_DIALOG_SIZE = (280, 180)
INPUT_DIALOG_MIN_SIZE = (260, 140)
INPUT_DIALOG_MAIN_LAYOUT_MARGINS = (15, 15, 15, 40)
INPUT_DIALOG_LAYOUT_SPACING = 12
INPUT_FIELD_MIN_HEIGHT = 30
INPUT_DIALOG_BTN_HEIGHT = 26
INPUT_DIALOG_BTN_MIN_WIDTH = 44

# ── Widget Sizes ──────────────────────────────────────────────────────

CHROME_BUTTON_SIZE = 28
HISTORY_ICON_SIZE = (16, 16)
HISTORY_BUTTON_SIZE = (28, 28)  # width, height for the 🕒 button

HISTORY_CARD_SPACING = 8
HISTORY_CARD_MARGIN_LEFT = 2
HISTORY_CARD_MARGIN_TOP = 4
HISTORY_CARD_MARGIN_RIGHT = 10
HISTORY_CARD_MARGIN_BOTTOM = 4
HISTORY_CARD_INNER_SPACING = 4
HISTORY_TEXT_META_SPACING = 0

# History dialog layout
HISTORY_HEADER_CARD_MARGINS = (20, 18, 20, 16)
HISTORY_HEADER_SPACING = 6
HISTORY_FOOTER_MARGINS = (16, 12, 16, 12)
HISTORY_FOOTER_SPACING = 12
HISTORY_STATS_GAP = 4
HISTORY_COUNT_BADGE_SIZE = (38, 38)
HISTORY_STATS_BAR_MIN_HEIGHT = 20
HISTORY_SEPARATOR_HEIGHT = 1

# Button heights
BTN_HEIGHT_SM = 26
BTN_HEIGHT_MD = 28
BTN_HEIGHT_LG = 32

# Button min widths
BTN_MIN_WIDTH_SM = 44
BTN_MIN_WIDTH_MD = 70
BTN_MIN_WIDTH_LG = 80
BTN_MIN_WIDTH_XL = 100

# Sidebar
SIDEBAR_BTN_HEIGHT = 32

# Progress bar
PROGRESS_BAR_HEIGHT = 22

# Drop indicator
DROP_INDICATOR_HEIGHT = 3

# Key sequence edit
KEY_SEQ_EDIT_WIDTH = 120

# Scroll areas
SCROLL_AREA_MIN_HEIGHT = 36
SCROLL_AREA_MAX_HEIGHT = 120

# ── Timer & Delay Intervals (ms) ──────────────────────────────────────

DEFERRED_UPDATE_CHECK_MS = 3000
TASK_REMINDER_CHECK_MS = 15_000
DEFERRED_WHATS_NEW_MS = 1000
TRAY_NOTIFICATION_COOLDOWN_MS = 10_000
RESIZE_DEBOUNCE_MS = 100
ESCAPE_DOUBLE_TAP_MS = 500
COPIED_LABEL_RESET_MS = 1200
TRAY_MESSAGE_DURATION_MS = 3000
DWM_SHADOW_DISABLE_DELAY_MS = 100
DWM_SHADOW_DISABLE_SECOND_MS = 500
EMPTY_STATE_BLINK_MS = 800
DEFERRED_RENDER_MS = 0

# ── Slider Ranges ─────────────────────────────────────────────────────

OPACITY_SLIDER_MIN = 30       # %
OPACITY_SLIDER_MAX = 100      # %
OPACITY_FLOOR = 0.30          # minimum window opacity (float)
OPACITY_DIVISOR = 100.0       # slider → float conversion

TEXT_SIZE_SLIDER_MIN = 16
TEXT_SIZE_SLIDER_MAX = 25

# ── Font Sizes (px) ───────────────────────────────────────────────────

FONT_SIZE_HINT = 10
FONT_SIZE_LABEL_SM = 11
FONT_SIZE_LABEL_MD = 12
FONT_SIZE_BODY = 13
FONT_SIZE_TITLE_SM = 13
FONT_SIZE_TITLE_MD = 14
FONT_SIZE_TITLE_LG = 16
FONT_SIZE_EMPTY_STATE_ARROW = 24

# ── Layout Margins & Spacing ──────────────────────────────────────────

MARGIN_STANDARD = (18, 18, 18, 18)  # standard dialogs
MARGIN_WIDE = (20, 18, 20, 18)      # themed message, export, feedback
MARGIN_SETTINGS_TAB = (6, 8, 6, 6)  # settings tab content

SPACING_SM = 6
SPACING_MD = 8
SPACING_LG = 10

# ── Border Radius (px) ────────────────────────────────────────────────
# NOTE: These should match theme.py radii dict. Listed here for
# inline stylesheet use where theme access isn't available.

RADIUS_WINDOW = 20
RADIUS_PANEL = 20
RADIUS_INPUT = 10
RADIUS_BUTTON = 8
RADIUS_TAB = 8
RADIUS_CHECKBOX = 4
RADIUS_MENU = 5
RADIUS_SMALL = 4

# ── Misc Widget Sizing ────────────────────────────────────────────────

DURATION_INPUT_MIN_WIDTH = 180
DURATION_APPLY_BTN_WIDTH = 50
DATE_EDIT_MIN_WIDTH = 130
TIME_EDIT_MIN_WIDTH = 90
REPEAT_SPIN_WIDTH = 90
EXPORT_COMBO_HEIGHT = 26
EXPORT_GROUP_SCROLL_MIN = 36
EXPORT_GROUP_SCROLL_MAX = 110
EXPORT_GROUP_CARD_MARGINS = (8, 6, 8, 6)
EXPORT_GROUP_CARD_SPACING = 2
EXPORT_GROUP_LIST_MARGINS = (14, 4, 4, 4)
EXPORT_GROUP_CHECKBOX_SPACING = 3
EXPORT_SCREEN_EDGE_MARGIN = 80
ADD_GROUP_BTN_SIZE = (32, 28)
SETTINGS_MAX_CLAMP_OFFSET = 80
SETTINGS_GLOW_BLUR_RADIUS = 30
SETTINGS_SHORTCUT_CARD_MARGINS = (10, 6, 10, 6)
SETTINGS_MAIN_LAYOUT_MARGINS = (14, 12, 14, 14)
SETTINGS_VALUE_LABEL_MIN_WIDTH = 48
SETTINGS_APPEARANCE_TAB_SPACING = 14
SETTINGS_EXPORT_GROUP_CONTENT_MARGINS = (14, 4, 4, 4)

# ── Priority Header (flat list) ───────────────────────────────────────

PRIORITY_HEADER_HEIGHT = 24
PRIORITY_HEADER_FONT_SIZE = 10
PRIORITY_HEADER_PADDING_H = 8
PRIORITY_DIVIDER_HEIGHT = 1
SECTION_DIVIDER_HEIGHT = 2

# Feedback dialog
FEEDBACK_MAX_CHARS = 1000
FEEDBACK_OVERLAP_RADIUS = 16
FEEDBACK_MAIN_LAYOUT_MARGINS = (20, 18, 20, 16)
FEEDBACK_LAYOUT_SPACING = 12
FEEDBACK_INPUT_CARD_MARGINS = (12, 10, 12, 12)
FEEDBACK_SNAPSHOT_CARD_MARGINS = (10, 8, 10, 8)
FEEDBACK_INPUT_MIN_HEIGHT = 110
FEEDBACK_SNAPSHOT_HEIGHT = 140
FEEDBACK_BTN_WIDTH = 110
FEEDBACK_SUBTITLE_OPACITY = 0.8
FEEDBACK_CHAR_COUNT_OPACITY = 0.6
FEEDBACK_FOOTER_OPACITY = 0.7

# Context menu
DIALOG_PLACEMENT_GAP = 15

WHATS_NEW_LINE_HEIGHT = 1.6
WHATS_NEW_LIST_ITEM_MARGIN = 2
WHATS_NEW_LIST_PADDING = 20
WHATS_NEW_HEADING_MARGIN_TOP = 8
WHATS_NEW_HEADING_MARGIN_BOTTOM = 4

# ── Download / Network ────────────────────────────────────────────────

DOWNLOAD_CHUNK_SIZE = 65536
URL_FETCH_TIMEOUT_S = 10
POWERSHELL_DOWNLOAD_TIMEOUT_S = 120
MB_DIVISOR = 1024 * 1024
DOWNLOAD_ERROR_MIN_SIZE = (400, 280)
DOWNLOAD_ERROR_WIDTH = 440
DOWNLOAD_ERROR_MAX_HEIGHT = 400
DOWNLOAD_ERROR_HEIGHT_BASE = 200
DOWNLOAD_ERROR_TEXT_MIN_H = 80

# ── Progress Bar ──────────────────────────────────────────────────────

PROGRESS_BAR_RADIUS = 6
PROGRESS_CHUNK_RADIUS = 5
PROGRESS_PCT_CAP = 99

# ── Dialog StyleSheet ─────────────────────────────────────────────────

DIALOG_BTN_ALPHA = 15
DIALOG_EDIT_ALPHA = 40
DIALOG_BTN_PAD_V = 6
DIALOG_BTN_PAD_H = 16
DIALOG_EDIT_PAD = 4
DIALOG_BORDER_WIDTH = 1

# ── Tray ──────────────────────────────────────────────────────────────

TRAY_EDGE_PADDING = 4

# ── History Icon Rendering ────────────────────────────────────────────

HISTORY_ICON_CANVAS = 16
HISTORY_ICON_FONT_PAD = 6
HISTORY_ICON_FONT_MIN = 10

# ── Hotkey Filter ─────────────────────────────────────────────────────

HOTKEY_START_ID = 1000

# ── GlowOverlay ───────────────────────────────────────────────────────

GLOW_RADIUS = 200
GLOW_INNER_STOP_1 = 25
GLOW_INNER_STOP_2 = 8
GLOW_INNER_STOP_3 = 0
GLOW_CORE_RATIO = 0.35
GLOW_OUTER_STOP_1 = 12
GLOW_OUTER_STOP_2 = 4
GLOW_OUTER_STOP_3 = 0
GLOW_HIDDEN_X = -9999

# ── Layout Spacing & Margins (main_window) ────────────────────────────

CENTRAL_WIDGET_SPACING = 6
TASKS_LAYOUT_SPACING = 6
FOOTER_SPACING = 8
FOOTER_MARGINS = (1, 0, 1, 0)
EMPTY_STATE_SPACING = 8
CENTRAL_WIDGET_MARGINS = (15, 15, 15, 5)

# ── Opacity Values ────────────────────────────────────────────────────

OPACITY_FULL = 0.5
OPACITY_ICONS = 0.4
OPACITY_DIM = 0.15

# ── Icon Sizes (inline) ───────────────────────────────────────────────

SETTINGS_ICON_SIZE = 16
HISTORY_BTN_ICON_SIZE = 12

# ── Escape Logic ──────────────────────────────────────────────────────

ESCAPE_PRESS_THRESHOLD = 2

# ── History Retention ─────────────────────────────────────────────────

SECONDS_PER_DAY = 86400

# ── Responsive Text ───────────────────────────────────────────────────

RESPONSIVE_TEXT_MIN_COL = 100
RESPONSIVE_TEXT_PCT = 0.4
RESPONSIVE_TEXT_VPAD = 14
RESPONSIVE_TEXT_LABEL_PAD = 5
RESPONSIVE_TEXT_STACK_MIN = 10

# ── Theme Widgets ─────────────────────────────────────────────────────

THEME_CARD_SIZE = (90, 60)
THEME_CARD_PREVIEW_HEIGHT = 30
THEME_CARD_MARGINS = (6, 6, 6, 6)
THEME_CARD_SPACING = 4
THEME_CARD_PREVIEW_RADIUS = 6
THEME_CARD_BORDER_WIDTH = 2

SETTINGS_CARD_MARGINS = (12, 10, 12, 10)
SETTINGS_CARD_CONTENT_SPACING = 2

TOGGLE_SWITCH_SIZE = (40, 24)
TOGGLE_SWITCH_RADIUS = 12
TOGGLE_KNOB_DIAMETER = 18
TOGGLE_KNOB_MARGIN = 3
TOGGLE_SWITCH_ROW_SPACING = 8

# ── Toast Notifications ──────────────────────────────────────────────

TOAST_DEFAULT_TIMEOUT_MS = 3000
TOAST_MAX_WIDTH = 600
TOAST_MARGINS = (14, 8, 14, 8)
TOAST_EDGE_MARGIN = 10
TOAST_RADIUS = 12
